// <auto-generated />
using System;
using AtlasSupply.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AtlasSupply.Infrastructure.Migrations
{
    [DbContext(typeof(AtlasSupplyDbContext))]
    [Migration("20260919095822_AddAgentToolAuditRecords")]
    partial class AddAgentToolAuditRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlasSupply.Domain.AgentToolAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Authorized")
                        .HasColumnType("boolean");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequiredScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Authorized");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToolName");

                    b.HasIndex("UserId");

                    b.ToTable("agent_tool_audit_records", (string)null);
                });

            modelBuilder.Entity("AtlasSupply.Domain.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("incidents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAtUtc = new DateTime(2026, 3, 5, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Carrier booking rollover pushed inbound cartons by four business days.",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Status = "InProgress",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Type = "Delay"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAtUtc = new DateTime(2026, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Incoming washer lot shows inconsistent zinc coating thickness.",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Status = "Open",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Type = "QualityIssue"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial steel plate lot arrived short by 12 units; backfill shipment confirmed.",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222202"),
                            ResolvedAtUtc = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Type = "ShortShipment"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            ClosedAtUtc = new DateTime(2025, 12, 24, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2025, 12, 21, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Forklift puncture damaged five bearing cartons during receiving.",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222206"),
                            ResolvedAtUtc = new DateTime(2025, 12, 22, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Type = "DamagedGoods"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            CreatedAtUtc = new DateTime(2026, 2, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Duplicate service ticket created during shift handoff.",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Status = "Cancelled",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111104"),
                            Type = "Other"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            CreatedAtUtc = new DateTime(2026, 3, 10, 7, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Supplier advised extended lead time on legacy controller components.",
                            Status = "Open",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111105"),
                            Type = "Delay"
                        });
                });

            modelBuilder.Entity("AtlasSupply.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            ApprovedAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            ReceivedAtUtc = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SubmittedAtUtc = new DateTime(2026, 1, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAtUtc = new DateTime(2026, 2, 3, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Submitted",
                            SubmittedAtUtc = new DateTime(2026, 2, 3, 13, 15, 0, 0, DateTimeKind.Utc),
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            ApprovedAtUtc = new DateTime(2026, 2, 11, 8, 20, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2026, 2, 10, 8, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            SubmittedAtUtc = new DateTime(2026, 2, 10, 10, 20, 0, 0, DateTimeKind.Utc),
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAtUtc = new DateTime(2026, 1, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            SubmittedAtUtc = new DateTime(2026, 1, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111105")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAtUtc = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Draft",
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            ApprovedAtUtc = new DateTime(2025, 12, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReceivedAtUtc = new DateTime(2025, 12, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SubmittedAtUtc = new DateTime(2025, 12, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            SupplierId = new Guid("11111111-1111-1111-1111-111111111102")
                        });
                });

            modelBuilder.Entity("AtlasSupply.Domain.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("purchase_order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Description = "M12 galvanized hex bolts",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Quantity = 500,
                            UnitPrice = 0.36m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Description = "M12 lock washers",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Quantity = 500,
                            UnitPrice = 0.08m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Description = "A36 steel plate 10mm",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Quantity = 80,
                            UnitPrice = 42.75m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            Description = "Structural angle L50x50x6",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Quantity = 120,
                            UnitPrice = 18.40m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            Description = "Double-wall shipping cartons",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Quantity = 1500,
                            UnitPrice = 1.22m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            Description = "Pallet stretch film 500mm",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Quantity = 200,
                            UnitPrice = 7.90m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            Description = "Control board rev C",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Quantity = 30,
                            UnitPrice = 185.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            Description = "Inbound dock scheduling service",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Quantity = 12,
                            UnitPrice = 320.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            Description = "Cross-dock handling support",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222205"),
                            Quantity = 10,
                            UnitPrice = 280.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            Description = "Sealed roller bearings 6205",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222206"),
                            Quantity = 240,
                            UnitPrice = 6.45m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            Description = "Bearing housing assemblies",
                            PurchaseOrderId = new Guid("22222222-2222-2222-2222-222222222206"),
                            Quantity = 60,
                            UnitPrice = 24.30m
                        });
                });

            modelBuilder.Entity("AtlasSupply.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            ContactEmail = "procurement@northwind-industrial.example",
                            IsActive = true,
                            Name = "Northwind Industrial Components"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            ContactEmail = "orders@harborsteel.example",
                            IsActive = true,
                            Name = "Harbor Steel Works"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            ContactEmail = "supply@silverline-packaging.example",
                            IsActive = true,
                            Name = "Silverline Packaging Co."
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            ContactEmail = "support@apex-logistics.example",
                            IsActive = false,
                            Name = "Apex Logistics Partners"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            ContactEmail = "contact@legacy-circuitry.example",
                            IsActive = false,
                            Name = "Legacy Circuitry Ltd."
                        });
                });

            modelBuilder.Entity("AtlasSupply.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Email = "readonly@atlas-supply.local",
                            NormalizedEmail = "READONLY@ATLAS-SUPPLY.LOCAL",
                            NormalizedUsername = "READONLY",
                            PasswordHash = "AQAAAAIAAYagAAAAEAUxTC+MIKE77PFUkpiSQ/Ns35XdfbWERmzqQ+Je7SGrLj26Co3+L7kF1eCp4yjU6w==",
                            Username = "readonly"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Email = "operator@atlas-supply.local",
                            NormalizedEmail = "OPERATOR@ATLAS-SUPPLY.LOCAL",
                            NormalizedUsername = "OPERATOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEAUxTC+MIKE77PFUkpiSQ/Ns35XdfbWERmzqQ+Je7SGrLj26Co3+L7kF1eCp4yjU6w==",
                            Username = "operator"
                        });
                });

            modelBuilder.Entity("AtlasSupply.Domain.UserScopeAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId", "Scope");

                    b.ToTable("user_scope_assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_scope_assignments_Scope", "\"Scope\" IN ('suppliers.list', 'suppliers.read', 'orders.delayed.read', 'incidents.create', 'knowledge.search')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Scope = "suppliers.list"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Scope = "suppliers.read"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Scope = "orders.delayed.read"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Scope = "knowledge.search"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Scope = "suppliers.list"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Scope = "suppliers.read"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Scope = "orders.delayed.read"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Scope = "incidents.create"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Scope = "knowledge.search"
                        });
                });

            modelBuilder.Entity("AtlasSupply.Infrastructure.Persistence.Knowledge.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Heading")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_l2_ops" });

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("AtlasSupply.Infrastructure.Persistence.Knowledge.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourcePath")
                        .IsUnique();

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("AtlasSupply.Domain.Incident", b =>
                {
                    b.HasOne("AtlasSupply.Domain.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AtlasSupply.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlasSupply.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("AtlasSupply.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlasSupply.Domain.PurchaseOrderItem", b =>
                {
                    b.HasOne("AtlasSupply.Domain.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlasSupply.Domain.UserScopeAssignment", b =>
                {
                    b.HasOne("AtlasSupply.Domain.User", null)
                        .WithMany("ScopeAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlasSupply.Infrastructure.Persistence.Knowledge.KnowledgeChunk", b =>
                {
                    b.HasOne("AtlasSupply.Infrastructure.Persistence.Knowledge.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AtlasSupply.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AtlasSupply.Domain.User", b =>
                {
                    b.Navigation("ScopeAssignments");
                });

            modelBuilder.Entity("AtlasSupply.Infrastructure.Persistence.Knowledge.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
